### ISSUE TITLE
77 parser cannot handle implicit do in a data list

### ISSUE THREAD

**Issue by traveltissues** [camfort/fortran-src#101]
```
       program foo
       integer var, i, arr(3)
       data (arr(i), i=1,3), var /1,2,3,4/
       end
```
will throw an error on parsing at `),` with the last parsed token being `TComma`. aiui this is valid 77 syntax for a data statement list. https://docs.oracle.com/cd/E19957-01/805-4939/6j4m0vn85/index.html

`DATA nlist / clist / [[,] nlist / clist /] ...`

**Comment by mrd** [comment]
If I'm understanding your question here correctly, then I don't believe that your example is valid syntax according to that webpage. The `nlist` portion containing the implied-do `(arr(i), i=1,3)` is not matched up with any `clist` because there is a comma immediately following it. If I rewrite it like so then it is ok:

      program foo
      integer var, i, arr(3)
      data (arr(i), i=1,3) /1,2,3/, var /1/
      end
