### ISSUE TITLE
Substring access of literals

### ISSUE THREAD

**Issue by traveltissues** [camfort/fortran-src#105]
The standard describes a substring as a contiguous portion of a character with type character and an array as a non-empty data sequence. It's not clear to me from that if that excludes accessing literal arrays. The documentation suggests that substrings should only be accessible via reference to a variable:
```fortran
character*4 c /'1234'/
character*2 s
s = c(1:2)
```
but several compilers will treat this as functionally equivalent
```fortran
character*2 s
s = '1234'(1:2)
```
which is not supported by fortran-src

**Comment by mrd** [comment]
We can probably do it. I'll have to see if there's any unforeseen consequences, but right now the reason it doesn't work is because our parsing rule for subscripts expects a variable and not any arbitrary expression. Alternatively I could expand it so that it accepts only variables and literal array/string expressions, but not any other arbitrary expressions.

I guess the question would be: is there also an interest in supporting references like `'12'//'34'(1:2)`?

**Comment by traveltissues** [comment]
it can definitely be supported, the question was whether upstream is willing to maintain it. As for the next, i think it should be supported if that syntax is allowed. Gfortran supports that

**Comment by mrd** [comment]
It looks more like gfortran has a bug.

      character*2 s
      s = '12'//'34'(2:3)
      print *,s

prints

> 12

if you attempt to add parentheses then gfortran throws an error

>        s = ('12'//'34')(2:3)
>             1
> Error: Invalid character in name at (1)

I will look at adding literal strings. Adding arbitrary expressions looks like it would require significant reworking of the grammar, to avoid myriad reduce/reduce conflicts, and the benefit seems unclear.

**Comment by mrd** [comment]
Let me know what you think of https://github.com/camfort/fortran-src/commit/6d6a5acceee3f36109fb19cbf8cb31738563178e

**Comment by traveltissues** [comment]
`  s = '12'//'34'(2:3)` , yeah i wouldn't expect that to be supported, is that a standard syntax?

> Let me know what you think of 6d6a5ac

thanks, i'll have a look

**Comment by traveltissues** [comment]
looks good, thanks @mrd
