### ISSUE TITLE
Support fixed source form in fortran 90

### ISSUE THREAD

**Issue by ProgramFan** [camfort/fortran-src#170]
Hello, I found that fortran-src will assume fortran 90 files being free form. But the fortran 90 standard support fixed form also and many code here uses both fixed source form and fortran features (modules), and they can not be parsed by fortran-src.

It is possible to make the fortran 90 parser handle fixed source form?

**Comment by dorchard** [comment]
Hi @ProgramFan, thanks for the issue. `fortran-src` should be handling fixed form for Fortran 90 fine. Do you have an example which is failing that we could look into?

**Comment by ProgramFan** [comment]
Sorry to reply late. I create a small sample to reproduce the issue. Save the following content into `sample_1.f` and parse it as fortran 90 source, the error will occur.

```fortran
      SUBROUTINE test_func()
      COMMON /TEST_COMMON/ variable1, variable2
     1 variable3
      TYPE(TEST_TYPE) :: test

      END
```

When parsing with `fortran-src -a parse -v Fortran90 sample_1.f`, an error will occur at the line continuation. The detailed error message is:

```
ProgramFilefortran-src: fortran-src: user error (sample_1.f, 3:8: sample_1.f: lexing failed.
Last parsed token: TIntegerLiteral (3:6)-(3:6) "1".)
```

It seems that fortran-src tries to lex the source as free-form sources, even when the file extension suggest it is in fixed soruce form.

**Comment by ProgramFan** [comment]
If possible, it would be nice to seperate the source form from the language selection with two options like `--fixed-form -v Fortran90`.

**Comment by raehik** [comment]
I see your problem! But I'm afraid supporting "full" fixed source form in Fortran 90 and onwards would be tricky. Fixed and free lexing is very different, and heavily integrated with the spec's syntax and our parsers.

We *do* support a "mixed form" that imitates fixed source form in F90 (and up). It's really just a set of guidelines to keep your syntax compatible between both forms, and not perfect. The problem in your case is continuations. If we were to follow the mixed form rules in JC Adams' Fortran 90 Handbook (pg.82), we could write:

```fortran-free-form
      SUBROUTINE test_func()
      COMMON /TEST_COMMON/ variable1, variable2                         &
     & , variable3
      TYPE(TEST_TYPE) :: test

      END
```

If you made this program F77-compliant (remove the DDT), it should be valid F77 and F90. However, fortran-src now won't parse it in F77, because we're relying on the parser ignoring all columns after 73. fortran-src chooses to ignore that limitation in the hopes of handling non-conforming programs. But it means we can't recognize this syntax hack!

In any case, the summary is that fortran-src already does the best it can, but fixed & free form are incompatible, and they're too tightly integrated with the language syntax to attempt generalizing the parsers over both lexers, Sorry!

**Comment by raehik** [comment]
Related, I keep wondering if we could solve some of our parsing woes by parsing to a "flat" AST first, then traversing that to generate the main AST. Allows for lots more configuration on what programs to accept (strict or lax on conformance), and more emphasis on post-parse transformations. It'd bump up parse times unless we can be clever about things, though.

**Comment by ProgramFan** [comment]
Thanks for the reply. I fully understand the situation and why it is hard to support both f90 and fixed form at the same time. So I gladly accept the explanation and the design choice of fortran-src. fortran-src is the only parser I encounter to be able to handle inter-symbol spaces in fixed-form fortran other than gcc and ifort (they are not parsers and do not expose their parse tree either). Handling inter-symbol spaces will require special lexing, and this might be the reason why the lexing in fortran-src is tightly coupled with the fortran version.

Thanks for creating such a wonderful tool for us to work with fortran.
