### ISSUE TITLE
DO LABEL WHILE not supported

### ISSUE THREAD

**Issue by dorchard** [camfort/fortran-src#34]
Fortran 90 standard allows the following kind of thing:

```
      program dowhile
      implicit none
      integer :: i = 0
      DO  200  WHILE (i .lt. 10)
         i = i + 1
  200  write (*,*), i
      end
```

We can't parse a DO WHILE with a label in it yet. Should we allow this in F77 extended too as well as F90?

**Comment by raehik** [comment]
Resurrecting this because the parsers indicate that this *should* be supported:

```
EXECUTABLE_STATEMENT :: { Statement A0 }
...
| do INTEGER_LITERAL MAYBE_COMMA while '(' EXPRESSION ')'
  { StDoWhile () (getTransSpan $1 $7) Nothing (Just $2) $6 }
...
```

Lexing your passage shows that the lexer fails to lex to a `TWhile`, instead finding a `TId _ "while"`. It appears to be because a `TWhile` can only be lexed following a `TDo` (whereas here it follows a `TIntegerLiteral _ "200"`).

Fixed with a test case in #164 .
